spring:
  datasource:
    primary:
      name: employees
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      # 指定时区，避免时区问题
      jdbc-url: jdbc:mysql://192.168.1.242:3306/employees?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&generateSimpleParameterMetadata=true
      username: root
      password: root
      hikari:
        minimum-idle: 10
        maximum-pool-size: 50
    secondary:
      name: employees
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://192.168.1.242:3306/ground?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&generateSimpleParameterMetadata=true
      username: root
      password: root
      hikari:
        minimum-idle: 10
        maximum-pool-size: 50
mybatis-plus:
  primary:
    mapper-locations: classpath*:mybatis/primary/*.xml
  secondary:
    mapper-locations: classpath*:mybatis/secondary/*.xml